-- Fix til fejl introduceret ved migrering til 1.13.0.. (KIH-986)
update questionnaire_group2questionnaire_header
set standard_schedule_intro_period_weeks = null
where STANDARD_SCHEDULE_TIMES_OF_DAY is null
and STANDARD_SCHEDULE_WEEKDAYS is null
and STANDARD_SCHEDULE_WEEKDAYS_INTRO_PERIOD is null
and STANDARD_SCHEDULE_WEEKDAYS_SECOND_PERIOD is null
and STANDARD_SCHEDULE_REMINDER_TIME is null
and STANDARD_SCHEDULE_BLUE_ALARM_TIME is null
and STANDARD_SCHEDULE_DAYS_IN_MONTH is null
and STANDARD_SCHEDULE_INTERVAL_IN_DAYS is null
and STANDARD_SCHEDULE_STARTING_DATE is null
and STANDARD_SCHEDULE_SPECIFIC_DATE is null
and standard_schedule_reminder_start_minutes is null
and standard_schedule_intro_period_weeks is not null;



CREATE TABLE [dbo].[PATIENT_OVERVIEW] (
  [ID] BIGINT IDENTITY NOT NULL,
  [VERSION] BIGINT NOT NULL,
  [PATIENT_ID] BIGINT NOT NULL,
  [NAME] NVARCHAR(1024) NOT NULL,
  [CPR] NVARCHAR(1024) NOT NULL,
  [NUMBER_OF_UNACKNOWLEDGED_QUESTIONNAIRES] INT NOT NULL,
  [QUESTIONNAIRE_SEVERITY] NVARCHAR(1024) NOT NULL,
  [MOST_SEVERE_QUESTIONNAIRE_NAME] VARCHAR(255),
  [MOST_SEVERE_QUESTIONNAIRE_DATE] datetime2(7),
  [BLUE_ALARM_TEXT] NVARCHAR(4000),
  [GREEN_QUESTIONNAIRE_IDS] NVARCHAR(4000),
  [NUMBER_OF_UNREAD_MESSAGES_TO_PATIENT] INT NOT NULL,
  [DATE_OF_OLDEST_UNREAD_MESSAGE_TO_PATIENT] datetime2(7),
  [NUMBER_OF_UNREAD_MESSAGES_FROM_PATIENT] INT NOT NULL,
  [DATE_OF_OLDEST_UNREAD_MESSAGE_FROM_PATIENT] datetime2(7),
  [IMPORTANT] bit NOT NULL
  )
GO

ALTER TABLE [dbo].[PATIENT_OVERVIEW] ADD CONSTRAINT [FK_PATIENT_OVERVIEW_PATIENT] FOREIGN KEY ([PATIENT_ID]) REFERENCES [dbo].[PATIENT] ([ID])
GO

CREATE UNIQUE INDEX [IDX_PATIENT_OVERVIEW_PATIENT_ID_UNIQUE] ON [dbo].[PATIENT_OVERVIEW]([PATIENT_ID])
GO

ALTER TABLE measurement ADD device_identification nvarchar(1024)
GO

ALTER TABLE patient_note DROP COLUMN remind_today
GO
